name: "Authenticate GCP, Fetch Secrets"
description: "Authenticate GCP and fetch secrets"

inputs:
  CREDENTIALS_JSON:
    description: "GCP Service Account JSON"
    required: true
  CONFIG_ENV:
    description: "Environment to fetch config from"
    required: true

runs:
  using: "composite"

  steps:
    - name: Authenticate Google Cloud
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ inputs.CREDENTIALS_JSON }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
